name: Build and Deploy Azure Static Web App

# This trigger has been changed to manual.
# To deploy, go to the "Actions" tab in GitHub and click "Run workflow".
on: 
  workflow_dispatch

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build App
        run: |
          npm install
          npm run build

      - name: List files for debugging
        run: ls -R dist

      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ISLAND_0BD510F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" 
          api_location: "" 
          output_location: "dist/bookstore-app" # This is our current guess. The "List files" step will confirm it.
          ###### End of Repository/Build Configurations ######

# Note: The "close_pull_request_job" has been removed as it is not needed for a manual workflow.
